// Code generated by protoc-gen-go-proxy. DO NOT EDIT.
// source: adviser.proto

package proxypb

import (
	"context"

	"github.com/effective-security/porto/pkg/retriable"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/promptviser/api/pb"
	"google.golang.org/grpc"
)

type proxyAdviserServer struct {
	srv pb.AdviserServer
}

type proxyAdviserClient struct {
	remote   pb.AdviserClient
	callOpts []grpc.CallOption
}

type postproxyAdviserClient struct {
	client retriable.PostRequester
}

// AdviserServerToClient returns pb.AdviserClient
func AdviserServerToClient(srv pb.AdviserServer) pb.AdviserClient {
	return &proxyAdviserServer{srv}
}

// NewAdviserClient returns instance of the AdviserClient
func NewAdviserClient(conn *grpc.ClientConn, callOpts []grpc.CallOption) pb.AdviserServer {
	return &proxyAdviserClient{
		remote:   pb.NewAdviserClient(conn),
		callOpts: callOpts,
	}
}

// NewAdviserClientFromProxy returns instance of AdviserClient
func NewAdviserClientFromProxy(proxy pb.AdviserClient) pb.AdviserServer {
	return &proxyAdviserClient{
		remote: proxy,
	}
}

// NewAdviserClientFromProxy returns instance of AdviserClient
func NewHTTPAdviserClient(client retriable.PostRequester) pb.AdviserServer {
	return &postproxyAdviserClient{
		client: client,
	}
}

// Submit data for analysis.
func (s *proxyAdviserServer) Submit(ctx context.Context, req *pb.SubmitRequest, opts ...grpc.CallOption) (*pb.SubmitResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.Submit(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// Submit data for analysis.
func (s *proxyAdviserClient) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.Submit(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// Submit data for analysis.
func (s *postproxyAdviserClient) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	var res pb.SubmitResponse
	path := pb.Adviser_Submit_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}
