// Code generated by protoc-gen-go-mock. DO NOT EDIT.
// source: adviser.proto

package mockpb

import (
	"context"

	"github.com/effective-security/promptviser/api/pb"
	"google.golang.org/protobuf/proto"
)

// MockAdviserServer for testing
type MockAdviserServer struct {
	pb.AdviserServer

	Reqs []proto.Message

	// If set, all calls return this error.
	Err error

	// responses to return if err == nil
	Resps []proto.Message
	Index int
}

// SetResponse sets a single response without errors
func (m *MockAdviserServer) SetResponse(r proto.Message) {
	m.Err = nil
	m.Resps = []proto.Message{r}
	m.Index = 0
}

// SetResponses sets responses without errors
func (m *MockAdviserServer) SetResponses(r []proto.Message) {
	m.Err = nil
	m.Resps = r
	m.Index = 0
}

func (m *MockAdviserServer) next() proto.Message {
	c := len(m.Resps)
	idx := m.Index
	m.Index++
	if idx >= c {
		idx = c - 1
	}
	return m.Resps[idx]
}

// Submit data for analysis.

func (m *MockAdviserServer) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.SubmitResponse), nil
}
