// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: adviser.proto

package httppb

import (
	"net/http"

	"github.com/effective-security/porto/restserver"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/porto/xhttp/marshal"
	"github.com/effective-security/promptviser/api/pb"
)

// GetAdviserHTTPHandler handles HTTP requests for Adviser service
func GetAdviserHTTPHandler(s pb.AdviserServer, withAccessCheck pb.CheckAccessFunc) restserver.Handle {
	return func(w http.ResponseWriter, r *http.Request, p restserver.Params) {
		action := r.URL.Path
		ctx := correlation.WithMetaFromRequest(r)

		var err error
		var res any

		req, _, err := pb.UnmarshalRequest(w, r)
		if err != nil {
			// UnmarshalRequest already writes error response
			return
		}

		if withAccessCheck != nil {
			err = withAccessCheck(ctx, req, action)
			if err != nil {
				marshal.WriteJSON(w, r, err)
				return
			}
		}

		switch action {

		case pb.Adviser_Submit_FullMethodName:
			res, err = s.Submit(ctx, req.(*pb.SubmitRequest))

		default:
			err = httperror.Malformed("invalid action: %s", action)
		}
		if err != nil {
			marshal.WriteJSON(w, r, err)
			return
		}

		marshal.WriteJSON(w, r, res)
	}
}
