// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: adviser.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_adviser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the job ID.
	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_adviser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_adviser_proto protoreflect.FileDescriptor

const file_adviser_proto_rawDesc = "" +
	"\n" +
	"\radviser.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x18es/api/annotations.proto\"#\n" +
	"\rSubmitRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\" \n" +
	"\x0eSubmitResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID2b\n" +
	"\aAdviser\x12W\n" +
	"\x06Submit\x12\x11.pb.SubmitRequest\x1a\x12.pb.SubmitResponse\"&\x82C\x06submit\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/pb.Adviser/SubmitB2Z0github.com/effective-security/promptviser/api/pbb\x06proto3"

var (
	file_adviser_proto_rawDescOnce sync.Once
	file_adviser_proto_rawDescData []byte
)

func file_adviser_proto_rawDescGZIP() []byte {
	file_adviser_proto_rawDescOnce.Do(func() {
		file_adviser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adviser_proto_rawDesc), len(file_adviser_proto_rawDesc)))
	})
	return file_adviser_proto_rawDescData
}

var file_adviser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adviser_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: pb.SubmitRequest
	(*SubmitResponse)(nil), // 1: pb.SubmitResponse
}
var file_adviser_proto_depIdxs = []int32{
	0, // 0: pb.Adviser.Submit:input_type -> pb.SubmitRequest
	1, // 1: pb.Adviser.Submit:output_type -> pb.SubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adviser_proto_init() }
func file_adviser_proto_init() {
	if File_adviser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adviser_proto_rawDesc), len(file_adviser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adviser_proto_goTypes,
		DependencyIndexes: file_adviser_proto_depIdxs,
		MessageInfos:      file_adviser_proto_msgTypes,
	}.Build()
	File_adviser_proto = out.File
	file_adviser_proto_goTypes = nil
	file_adviser_proto_depIdxs = nil
}
