// Code generated by protoc-gen-go-json. DO NOT EDIT.

package pb

import (
	"fmt"
	sync "sync"

	"github.com/effective-security/protoc-gen-go/api"
	"google.golang.org/protobuf/types/known/emptypb"
)

var Empty_MessageDescription = &api.MessageDescription{
	Name:     "Empty",
	FullName: "google.protobuf.Empty",
	Documentation: `A generic empty message that you can re-use to avoid defining duplicated
empty messages in your APIs. A typical example is to use it as the request
or the response type of an API method. For instance:
service Foo {
rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
}`,
	Fields: []*api.FieldMeta{},
}

var ServerStatus_MessageDescription = &api.MessageDescription{
	Name:          "ServerStatus",
	Display:       "Server Status",
	FullName:      "pb.ServerStatus",
	Documentation: `ServerStatus provides server status information`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Name",
			FullName:      "pb.ServerStatus.Name",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Name of the server or application.`,
		},
		{
			Name:          "Nodename",
			FullName:      "pb.ServerStatus.Nodename",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Nodename is the human-readable name of the cluster member,
or empty for single host.`,
		},
		{
			Name:          "Hostname",
			FullName:      "pb.ServerStatus.Hostname",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Hostname is operating system's host name.`,
		},
		{
			Name:          "ListenUrls",
			FullName:      "pb.ServerStatus.ListenUrls",
			Display:       "Listen Urls",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `ListenURLs is the list of URLs the service is listening on.`,
		},
		{
			Name:          "StartedAt",
			FullName:      "pb.ServerStatus.StartedAt",
			Display:       "Started At",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `StartedAt is the time in RFC3339 format.`,
		},
	},
}

var ServerStatusResponse_MessageDescription = &api.MessageDescription{
	Name:          "ServerStatusResponse",
	Display:       "Server Status Response",
	FullName:      "pb.ServerStatusResponse",
	Documentation: `ServerStatusResponse returns status and version`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Status",
			FullName:      "pb.ServerStatusResponse.Status",
			Type:          "struct",
			StructName:    "pb.ServerStatus",
			SearchType:    "flat_object",
			Documentation: `Status of the server.`,
		},
		{
			Name:          "Version",
			FullName:      "pb.ServerStatusResponse.Version",
			Type:          "struct",
			StructName:    "pb.ServerVersion",
			SearchType:    "flat_object",
			Documentation: `Version of the server.`,
		},
		{
			Name:       "Pods",
			FullName:   "pb.ServerStatusResponse.Pods",
			Type:       "map",
			StructName: "pb.ServerStatusResponse.PodsEntry",
			SearchType: "flat_object",
		},
	},
}

var ServerStatusResponse_PodsEntry_MessageDescription = &api.MessageDescription{
	Name:     "ServerStatusResponse_PodsEntry",
	Display:  "Pods Entry",
	FullName: "pb.ServerStatusResponse.PodsEntry",
	Fields: []*api.FieldMeta{
		{
			Name:          "Key",
			FullName:      "pb.ServerStatusResponse.PodsEntry.Key",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Required:      true,
		},
		{
			Name:          "Value",
			FullName:      "pb.ServerStatusResponse.PodsEntry.Value",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Required:      true,
		},
	},
}

var ServerVersion_MessageDescription = &api.MessageDescription{
	Name:          "ServerVersion",
	Display:       "Server Version",
	FullName:      "pb.ServerVersion",
	Documentation: `ServerVersion provides server build and runtime version`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Build",
			FullName:      "pb.ServerVersion.Build",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Build is the server build version.`,
		},
		{
			Name:          "Runtime",
			FullName:      "pb.ServerVersion.Runtime",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Runtime is the runtime version.`,
		},
	},
}

// MessageAllocator defines constructor to allocate Protobuf message
type MessageAllocator func() any

var (
	initMessageDescriptionOnce sync.Once
	messageDescriptions        = map[string]*api.MessageDescription{
		"google.protobuf.Empty":             Empty_MessageDescription,
		"pb.ServerStatus":                   ServerStatus_MessageDescription,
		"pb.ServerStatusResponse":           ServerStatusResponse_MessageDescription,
		"pb.ServerStatusResponse.PodsEntry": ServerStatusResponse_PodsEntry_MessageDescription,
		"pb.ServerVersion":                  ServerVersion_MessageDescription,
	}

	messageAllocators = map[string]MessageAllocator{
		"google.protobuf.Empty":             func() any { return new(emptypb.Empty) },
		"pb.ServerStatus":                   func() any { return new(ServerStatus) },
		"pb.ServerStatusResponse":           func() any { return new(ServerStatusResponse) },
		"pb.ServerStatusResponse.PodsEntry": func() any { return make(map[string]string) },
		"pb.ServerVersion":                  func() any { return new(ServerVersion) },
	}
)

func (m *ServerStatusResponse) GetMessageDescription() *api.MessageDescription {
	return ServerStatusResponse_MessageDescription
}
func (m *ServerVersion) GetMessageDescription() *api.MessageDescription {
	return ServerVersion_MessageDescription
}

func GetMessageDescriptions() map[string]*api.MessageDescription {
	// Update the message Fields with the nested messages
	initMessageDescriptionOnce.Do(func() {
		for _, md := range messageDescriptions {
			for _, field := range md.Fields {
				if field.Fields == nil && (field.Type == "struct" || field.Type == "[]struct" || field.Type == "object" || field.Type == "[]object") {
					if msgDescr, ok := messageDescriptions[field.StructName]; ok {
						field.Fields = msgDescr.Fields
					}
				}
			}
		}
	})
	return messageDescriptions
}

func CreateMessage(fullname string) any {
	allocator := messageAllocators[fullname]
	if allocator == nil {
		panic(fmt.Sprintf("allocator for %s not found", fullname))
	}
	return allocator()
}

func GetMessageDescription(fullname string) *api.MessageDescription {
	return GetMessageDescriptions()[fullname]
}

func init() {
	_ = GetMessageDescriptions()
}
